let patients = [
    {
        MeditechEDM: {
            CTAS: "3",
            ChiefComplaint: "Abdo Pain,Mod,+/- Episod N&V",
            DepartDisposition: "Admitted",
            ArrivalTime: "02-Dec-2030 15:23",
            TriageTime: "02-Dec-2030 15:28",
            PhysicianInitialAssessmentTime: "02-Dec-2030 15:43",
            AdmittedTime: "02-Dec-2030 16:42",
        },
        ADM: {
            AdmitTime: "02-Dec-2030 16:42",
            AdmitUnit: "ED Unit #1",
            AdmitLocation: "ED Location #1",
            AdmitRoom: "ED Room #1",
            AdmitBed: "ED Bed #1",
            AdmittingPhysician: "Physician #1",
            AdmissionService: "Medicine",
            DischargeTime: "17-Feb-2031 13:14",
            DischargeUnit: "Hospital Unit #2",
            DischargeLocation: "Hospital Location #2",
            DischargeRoom: "Hospital Room #2",
            DischargeBed: "Hospital BHospital #2",
            DischargePhysician: "Physician #2",
            DischargeService: "Medicine",
        },
        OrderEntry: [
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "02-Dec-2030",
                Category: "Laboratory",
                Procedure: "Urine Routine (Urinalysis)",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "02-Dec-2030",
                Category: "Computed Tomography",
                Procedure: "Abdo Pelvis Renal Colic (KUB)",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "02-Dec-2030",
                Category: "Dietary",
                Procedure: "Nothing By Mouth",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Ammonia",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "02-Dec-2030",
                ServiceDate: "02-Dec-2030",
                Category: "Cardiology",
                Procedure: "ECG - Adult (12 Lead)",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Troponin I",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Cardiology",
                Procedure: "ECG - Adult (12 Lead)",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Troponin I",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Laboratory",
                Procedure: "Ionized Calcium Profile",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "03-Dec-2030",
                ServiceDate: "03-Dec-2030",
                Category: "Laboratory",
                Procedure: "Urine Drugs of Abuse Screen",
            },
            {
                OrderDate: "04-Dec-2030",
                ServiceDate: "04-Dec-2030",
                Category: "Radiography",
                Procedure: "Abdomen Multi Views",
            },
            {
                OrderDate: "04-Dec-2030",
                ServiceDate: "05-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "04-Dec-2030",
                ServiceDate: "05-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Ammonia",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "05-Dec-2030",
                Category: "Computed Tomography",
                Procedure: "Abdomen Pelvis Contrast",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "05-Dec-2030",
                Category: "Dietary",
                Procedure: "Nothing By Mouth",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Radiography",
                Procedure: "Chest (CXR)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "05-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Group & Screen",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lipase",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Cryoprecipitated AHF",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Plasma",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Platelets",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Red Blood Cells (Crossmatch)",
            },
            {
                OrderDate: "06-Dec-2030",
                ServiceDate: "06-Dec-2030",
                Category: "Social Work",
                Procedure: "Social Work Referral",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Alanine Aminotransferase",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Albumin",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Alkaline Phosphatase",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "AST (SGOT)",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Bilirubin, Total",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Calcium",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Gamma Glutamyl Transferase",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Laboratory",
                Procedure: "Triglycerides",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "07-Dec-2030",
                Category: "Dietitian Referrals",
                Procedure: "Nutrition Assessment",
            },
            {
                OrderDate: "07-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "TPN Orders - Day 1, 2 and 3",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Albumin 25%",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Albumin 5%",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Rapid Arterial Metabolic Panel",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Tissue Culture & Gram Stain",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Wound Deep Culture & Gram",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Quantitative Fibrinogen",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Rapid Arterial Metabolic Panel",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Rapid Arterial Metabolic Panel",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Quantitative Fibrinogen",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Albumin 25%",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Dietitian Referrals",
                Procedure: "Nutrition Assessment",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Physiotherapy",
                Procedure: "PT Inpatient Referral",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Social Work",
                Procedure: "Social Work Referral",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Sputum Culture & Gram Stain",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Cardiology",
                Procedure: "ECG - Adult (12 Lead)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Creatine Kinase (CPK)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Ionized Calcium Profile",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate Dehydrogenase (LDH)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Triglycerides",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Troponin I",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Blood Culture (Pt's 6 and up)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Urine Culture",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Laboratory",
                Procedure: "Blood Gas, Arterial (ABG)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "MRSA Screen",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Microbiology",
                Procedure: "Multiresistant organism screen",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "08-Dec-2030",
                Category: "Radiography",
                Procedure: "Chest Portable",
            },
            {
                OrderDate: "08-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Blood Gas, Arterial (ABG)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Blood Gas, Arterial (ABG)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Albumin 5%",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Radiography",
                Procedure: "Chest Portable",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Radiography",
                Procedure: "Chest Portable",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "09-Dec-2030",
                ServiceDate: "09-Dec-2030",
                Category: "Laboratory",
                Procedure: "Potassium",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Transfusion Medical Laboratory",
                Procedure: "Albumin 5%",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "10-Dec-2030",
                ServiceDate: "10-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Ammonia",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "C-Reactive Protein  (CRP)",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "11-Dec-2030",
                ServiceDate: "11-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Lactate: Lactic Acid",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Laboratory",
                Procedure: "TPN Orders - Monday",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Infectious Disease (SMH)",
                Procedure: "Infectious Disease Consult",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "12-Dec-2030",
                Category: "Dietary",
                Procedure: "Nothing By Mouth",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "13-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "13-Dec-2030",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "12-Dec-2030",
                ServiceDate: "13-Dec-2030",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "13-Dec-2030",
                ServiceDate: "13-Dec-2030",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "13-Dec-2030",
                ServiceDate: "14-Dec-2030",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "14-Dec-2030",
                ServiceDate: "14-Dec-2030",
                Category: "RAD - Special Procedures",
                Procedure: "Perc Fluid Drainage Abdomen US",
            },
            {
                OrderDate: "14-Dec-2030",
                ServiceDate: "15-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "14-Dec-2030",
                ServiceDate: "15-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "14-Dec-2030",
                ServiceDate: "14-Dec-2030",
                Category: "Dietary",
                Procedure: "Fibre Restricted",
            },
            {
                OrderDate: "14-Dec-2030",
                ServiceDate: "14-Dec-2030",
                Category: "Laboratory",
                Procedure: "INR (PT)",
            },
            {
                OrderDate: "16-Dec-2030",
                ServiceDate: "17-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "16-Dec-2030",
                ServiceDate: "17-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "17-Dec-2030",
                ServiceDate: "18-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "18-Dec-2030",
                ServiceDate: "18-Dec-2030",
                Category: "Social Work",
                Procedure: "Social Work Referral",
            },
            {
                OrderDate: "19-Dec-2030",
                ServiceDate: "19-Dec-2030",
                Category: "Physiotherapy",
                Procedure: "PT Inpatient Referral",
            },
            {
                OrderDate: "19-Dec-2030",
                ServiceDate: "19-Dec-2030",
                Category: "Wound Care Program",
                Procedure: "Wound Care Referral",
            },
            {
                OrderDate: "19-Dec-2030",
                ServiceDate: "20-Dec-2030",
                Category: "Computed Tomography",
                Procedure: "Abdomen Pelvis Contrast",
            },
            {
                OrderDate: "20-Dec-2030",
                ServiceDate: "21-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "20-Dec-2030",
                ServiceDate: "21-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "21-Dec-2030",
                ServiceDate: "21-Dec-2030",
                Category: "Dietary",
                Procedure: "Sodium Restricted  2 gm",
            },
            {
                OrderDate: "22-Dec-2030",
                ServiceDate: "22-Dec-2030",
                Category: "Wound Care Program",
                Procedure: "Wound Care Referral",
            },
            {
                OrderDate: "24-Dec-2030",
                ServiceDate: "25-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "24-Dec-2030",
                ServiceDate: "25-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "27-Dec-2030",
                ServiceDate: "28-Dec-2030",
                Category: "Laboratory",
                Procedure: "Chem 7 - Glu R,Urea,Crea,Lytes",
            },
            {
                OrderDate: "27-Dec-2030",
                ServiceDate: "28-Dec-2030",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "27-Dec-2030",
                ServiceDate: "27-Dec-2030",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "28-Dec-2030",
                ServiceDate: "28-Dec-2030",
                Category: "Dietary",
                Procedure: "Sodium Restricted  2 gm",
            },
            {
                OrderDate: "29-Dec-2030",
                ServiceDate: "30-Dec-2030",
                Category: "Laboratory",
                Procedure: "Creatine Kinase (CPK)",
            },
            {
                OrderDate: "29-Dec-2030",
                ServiceDate: "06-Jan-2031",
                Category: "Laboratory",
                Procedure: "Creatine Kinase (CPK)",
            },
            {
                OrderDate: "31-Dec-2030",
                ServiceDate: "31-Dec-2030",
                Category: "Laboratory",
                Procedure: "D-Dimer",
            },
            {
                OrderDate: "31-Dec-2030",
                ServiceDate: "02-Jan-2031",
                Category: "Ultrasonography",
                Procedure: "Dopp Low Extr Ven Bilat/scan",
            },
            {
                OrderDate: "01-Jan-2031",
                ServiceDate: "02-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "01-Jan-2031",
                ServiceDate: "02-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "01-Jan-2031",
                ServiceDate: "02-Jan-2031",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "01-Jan-2031",
                ServiceDate: "02-Jan-2031",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "01-Jan-2031",
                ServiceDate: "02-Jan-2031",
                Category: "Laboratory",
                Procedure: "C-Reactive Protein  (CRP)",
            },
            {
                OrderDate: "03-Jan-2031",
                ServiceDate: "05-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Jan-2031",
                ServiceDate: "03-Jan-2031",
                Category: "Ultrasonography",
                Procedure: "Abdomen",
            },
            {
                OrderDate: "03-Jan-2031",
                ServiceDate: "05-Jan-2031",
                Category: "Computed Tomography",
                Procedure: "Abdomen Pelvis Contrast",
            },
            {
                OrderDate: "04-Jan-2031",
                ServiceDate: "04-Jan-2031",
                Category: "Radiography",
                Procedure: "Kidneys Ureters Bladder (KUB)",
            },
            {
                OrderDate: "05-Jan-2031",
                ServiceDate: "05-Jan-2031",
                Category: "Microbiology",
                Procedure: "Urine Culture",
            },
            {
                OrderDate: "05-Jan-2031",
                ServiceDate: "05-Jan-2031",
                Category: "Therapeutic Recreation",
                Procedure: "Therapeutic Rec Referral",
            },
            {
                OrderDate: "06-Jan-2031",
                ServiceDate: "06-Jan-2031",
                Category: "Dietary",
                Procedure: "Sodium Restricted  2 gm",
            },
            {
                OrderDate: "07-Jan-2031",
                ServiceDate: "08-Jan-2031",
                Category: "Laboratory",
                Procedure: "Calcium",
            },
            {
                OrderDate: "07-Jan-2031",
                ServiceDate: "08-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "07-Jan-2031",
                ServiceDate: "08-Jan-2031",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "07-Jan-2031",
                ServiceDate: "08-Jan-2031",
                Category: "Laboratory",
                Procedure: "Phosphorus (Phosphate)",
            },
            {
                OrderDate: "11-Jan-2031",
                ServiceDate: "11-Jan-2031",
                Category: "Laboratory",
                Procedure: "Urine Drugs of Abuse Screen",
            },
            {
                OrderDate: "12-Jan-2031",
                ServiceDate: "12-Jan-2031",
                Category: "Infectious Disease (SMH)",
                Procedure: "Infectious Disease Consult",
            },
            {
                OrderDate: "13-Jan-2031",
                ServiceDate: "13-Jan-2031",
                Category: "Laboratory",
                Procedure: "Urine Drugs of Abuse Screen",
            },
            {
                OrderDate: "16-Jan-2031",
                ServiceDate: "17-Jan-2031",
                Category: "Laboratory",
                Procedure: "Creatine Kinase (CPK)",
            },
            {
                OrderDate: "16-Jan-2031",
                ServiceDate: "17-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "16-Jan-2031",
                ServiceDate: "17-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "16-Jan-2031",
                ServiceDate: "17-Jan-2031",
                Category: "Laboratory",
                Procedure: "Liver Function Tests (LFT)",
            },
            {
                OrderDate: "17-Jan-2031",
                ServiceDate: "19-Jan-2031",
                Category: "Computed Tomography",
                Procedure: "Abdomen Pelvis Contrast",
            },
            {
                OrderDate: "19-Jan-2031",
                ServiceDate: "24-Jan-2031",
                Category: "Laboratory",
                Procedure: "Creatine Kinase (CPK)",
            },
            {
                OrderDate: "23-Jan-2031",
                ServiceDate: "24-Jan-2031",
                Category: "Laboratory",
                Procedure: "C-Reactive Protein  (CRP)",
            },
            {
                OrderDate: "23-Jan-2031",
                ServiceDate: "24-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "23-Jan-2031",
                ServiceDate: "24-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "24-Jan-2031",
                ServiceDate: "25-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "24-Jan-2031",
                ServiceDate: "25-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Alanine Aminotransferase",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Alkaline Phosphatase",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "AST (SGOT)",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Bilirubin, Total",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Gamma Glutamyl Transferase",
            },
            {
                OrderDate: "26-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Social Work",
                Procedure: "Social Work Referral",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Calcium",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Lactate Dehydrogenase (LDH)",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Partial Thromboplastin Time",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Peripheral Blood Film Smear",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Retic Count",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "27-Jan-2031",
                Category: "Laboratory",
                Procedure: "Protein Electrophoresis",
            },
            {
                OrderDate: "27-Jan-2031",
                ServiceDate: "28-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "28-Jan-2031",
                ServiceDate: "28-Jan-2031",
                Category: "Laboratory",
                Procedure: "Urine Protein Electrph  Random",
            },
            {
                OrderDate: "30-Jan-2031",
                ServiceDate: "30-Jan-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "06-Feb-2031",
                ServiceDate: "07-Feb-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "06-Feb-2031",
                ServiceDate: "07-Feb-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "11-Feb-2031",
                ServiceDate: "11-Feb-2031",
                Category: "Microbiology",
                Procedure: "Wound Superficial Cult & Gram",
            },
            {
                OrderDate: "12-Feb-2031",
                ServiceDate: "12-Feb-2031",
                Category: "Laboratory",
                Procedure: "Chem 6 - Urea,Crea,Lytes",
            },
            {
                OrderDate: "12-Feb-2031",
                ServiceDate: "12-Feb-2031",
                Category: "Laboratory",
                Procedure: "Complete Blood Count (CBC)",
            },
            {
                OrderDate: "17-Feb-2031",
                ServiceDate: "17-Feb-2031",
                Category: "Social Work",
                Procedure: "Social Work Referral",
            },
        ],
        Appointments: [
            {
                Date: "10-Mar-2031",
                Description: "CT ANGIO THORAX CONTRAST(PULM)",
                Doctor: "Doctor #1",
                Location: "Location #1",
                Duration: "15 min",
            },
            {
                Date: "14-Mar-2031",
                Description: "NM BONE-WB INJ",
                Doctor: "Doctor #1",
                Location: "Location #2",
                Duration: "10 min",
            },
            {
                Date: "14-Mar-2031",
                Description: "NM BONE-WB",
                Doctor: "Doctor #1",
                Location: "Location #2",
                Duration: "45 min",
            },
            {
                Date: "14-Mar-2031",
                Description: "RA SKELETAL SURVEY ROUTINE",
                Doctor: "Doctor #2",
                Location: "Location #3",
                Duration: "60 min",
            },
            {
                Date: "15-Mar-2031",
                Description: "LB BONE MARROW",
                Doctor: "Doctor #3",
                Location: "Location #4",
                Duration: "60 min",
            },
            {
                Date: "28-Mar-2031",
                Description: "CT EXTREMITY UPPER LT",
                Doctor: "Doctor #4",
                Location: "Location #5",
                Duration: "15 min",
            },
            {
                Date: "08-Dec-2030",
                Description: "Lysis Abd Adhesions Laparoscop",
                Doctor: "Doctor #5",
                Location: "Location #6",
                Duration: "235 min",
            },
            {
                Date: "14-Dec-2030",
                Description: "RS PERC FLUID DRAINAGE ABD US",
                Doctor: "Doctor #6",
                Location: "Location #3",
                Duration: "45 min",
            },
            {
                Date: "20-Dec-2030",
                Description: "CT ABD PELVIS CONTRAST",
                Doctor: "Doctor #7",
                Location: "Location #3",
                Duration: "15 min",
            },
            {
                Date: "02-Jan-2031",
                Description: "US DOP LOW EXTR VENOUS BIL",
                Doctor: "Doctor #8",
                Location: "Location #3",
                Duration: "45 min",
            },
            {
                Date: "03-Jan-2031",
                Description: "US ABDOMEN",
                Doctor: "Doctor #8",
                Location: "Location #3",
                Duration: "45 min",
            },
            {
                Date: "05-Jan-2031",
                Description: "CT ABD PELVIS CONTRAST",
                Doctor: "Doctor #9",
                Location: "Location #3",
                Duration: "15 min",
            },
            {
                Date: "06-Jan-2031",
                Description: "AC SCOPE,CYSTOSCOPY-FLEX",
                Doctor: "Doctor #10",
                Location: "Location #7",
                Duration: "15 min",
            },
            {
                Date: "19-Jan-2031",
                Description: "CT ABD PELVIS CONTRAST",
                Doctor: "Doctor #11",
                Location: "Location #3",
                Duration: "15 min",
            },
        ],
        EDMLocationHistory: [
            {
                StartDate: "02-Dec-2030 15:28",
                EndDate: "02-Dec-2030 15:46",
                From: "Emergency Room #1",
                To: "Emergency Room #2",
                Duration: "0.3 days",
            },
            {
                StartDate: "02-Dec-2030 15:46",
                EndDate: "02-Dec-2030 16:02",
                From: "Emergency Room #2",
                To: "Emergency Room #3",
                Duration: "0.3 days",
            },
            {
                StartDate: "02-Dec-2030 16:02",
                EndDate: "02-Dec-2030 18:52",
                From: "Emergency Room #3",
                To: "Emergency Room #4",
                Duration: "2.8 days",
            },
            {
                StartDate: "02-Dec-2030 18:52",
                EndDate: "03-Dec-2030 12:40",
                From: "Emergency Room #4",
                To: "Emergency Room #5",
                Duration: "17.8 days",
            },
            {
                StartDate: "03-Dec-2030 12:40",
                EndDate: "03-Dec-2030 13:09",
                From: "Emergency Room #5",
                To: "Emergency Room #6",
                Duration: "0.5 days",
            },
            {
                StartDate: "03-Dec-2030 13:09",
                EndDate: "06-Dec-2030 22:39",
                From: "Emergency Room #6",
                To: "Hospital Room #1",
                Duration: "81.5 days",
            },
        ],
        ADMLocationHistory: [
            {
                StartDate: "06-Dec-2030 22:39",
                EndDate: "08-Dec-2030 16:35",
                From: "Hospital Room #1",
                To: "Hospital Room #2",
                Duration: "1.7 days",
            },
            {
                StartDate: "08-Dec-2030 16:35",
                EndDate: "08-Dec-2030 20:44",
                From: "Hospital Room #2",
                To: "Hospital Room #3",
                Duration: "0.2 days",
            },
            {
                StartDate: "08-Dec-2030 20:44",
                EndDate: "10-Dec-2030 20:54",
                From: "Hospital Room #3",
                To: "Hospital Room #4",
                Duration: "2.0 days",
            },
            {
                StartDate: "10-Dec-2030 20:54",
                EndDate: "29-Dec-2030 17:25",
                From: "Hospital Room #4",
                To: "Hospital Room #5",
                Duration: "18.9 days",
            },
            {
                StartDate: "29-Dec-2030 17:25",
                EndDate: "17-Feb-2031 13:14",
                From: "Hospital Room #5",
                To: "Discharged",
                Duration: "49.8 days",
            },
        ],
        Surgeries: [
            {
                SurgeryRoom: "Room #1",
                Surgeon: "Surgeon #1",
                SurgeonSpecialty: "Internal Medicine",
                Anaesthetist: "Anaesthetist #1",
                ProcedureDescription: "EGD with Banding",
                Status: "Urgent",
                PatientInRoom: "02-Dec-2030 17:06",
                ProcedureStart: "02-Dec-2030 17:14",
                TimeOpen: "NULL",
                TimeClose: "NULL",
                ProcedureEnds: "02-Dec-2030 17:21",
                PatientOutRoom: "02-Dec-2030 17:23",
            },
            {
                SurgeryRoom: "Room #2",
                Surgeon: "Surgeon #2",
                SurgeonSpecialty: "Surgery",
                Anaesthetist: "Anaesthetist #2",
                ProcedureDescription: "Small Bowel Resection, EXTENSIVE LYSIS",
                Status: "Elective",
                PatientInRoom: "08-Dec-2030 13:10",
                ProcedureStart: "08-Dec-2030 13:28",
                TimeOpen: "08-Dec-2030 13:50",
                TimeClose: "08-Dec-2030 19:42",
                ProcedureEnds: "08-Dec-2030 20:00",
                PatientOutRoom: "08-Dec-2030 20:15",
            },
        ]
    },
];



