ECG-Adult(12Lead)
Chem7-GluR,Urea,Crea,Lytes
CompleteBloodCount(CBC)
INR(PT)
TroponinI
C-ReactiveProtein(CRP)
D-Dimer
LiverFunctionTests(LFT)
TroponinI
Chest(CXR)
BtypeNatriureticProtein
General
Chem6-Urea,Crea,Lytes
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
AngioThoraxContrast(Pulm)
Albumin
Calcium
PeripheralBloodFilmSmear
Protein(Total)
ReticCount
BONE
ProteinElectrophoresis
UrineProteinElectrphRandom
UrineRoutine(Urinalysis)
MRSAScreen
SkeletalSurveyRoutine
BoneMarrowBooking
Calcium
Chem6-Urea,Crea,Lytes
Beta2Microglobulin
Chem4-Lytes(Na,K,Cl,Bicar)
CompleteBloodCount(CBC)
Creatinine(EGFR)
Ferritin
FreelightChains,Serum
HepBSurfaceAntigen-Active
HepCAntibody
HIVSerology
IonizedCalciumProfile
LactateDehydrogenase(LDH)
ParathyroidHormone,Intact
ReticCount
VitaminB12
CompleteBloodCount(CBC)
ReticCount
PhysiotherapyReferral
Chem7-GluR,Urea,Crea,Lytes
CompleteBloodCount(CBC)
IonizedCalciumProfile
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
PhysiotherapyReferral
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
BloodGas,Arterial(ABG)
NutritionAssessment
OccupationalTherapyReferral
PhysiotherapyReferral
ShoulderLt
OccupationalTherapyReferral
ExtremityUpperLt
Chem6-Urea,Crea,Lytes
IonizedCalciumProfile
HumerusLt
Group&Screen
RedBloodCells(Crossmatch)
BtypeNatriureticProtein
Ferritin
IronStudiesProfile
Magnesium
PeripheralBloodFilmSmear
Phosphorus(Phosphate)
ReticCount
Chest(CXR)
ECG-Adult(12Lead)
CompleteBloodCount(CBC)
INR(PT)
PartialThromboplastinTime
PartialThromboplastinTime
PartialThromboplastinTime
PartialThromboplastinTime
PartialThromboplastinTime
FluoroUpperExtLtSpecialist
HumerusLt
CompleteBloodCount(CBC)
INR(PT)
PartialThromboplastinTime
ExtremityUpperLt
General
FluoroUpperExtLtSpecialist
HumerusLt
NothingByMouth
CompleteBloodCount(CBC)
ChestPortable
Chest(CXR)
HomeHealthLiasonReferral
General
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
Chest(CXR)
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
ImmunoglobulinA(IGA)
ImmunoglobulinG(IgG)
ImmunoglobulinM(IGM)
IonizedCalciumProfile
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
CompleteBloodCount(CBC)
Chem6-Urea,Crea,Lytes
CompleteBloodCount(CBC)
LiverFunctionTests(LFT)
