let patients = [
    {
        name: "james john",
        labTests: [
        ],
        EDM: [
            {
                CTAS: "2",
                ChiefComplaint: "Chest Pain, Cardiac Feature",
                DepartDisposition: "Admitted",
                ArrivalTime: "09-Mar-2031 09:55",
                TriageTime: "09-Mar-2031 09:59",
                PhysicianInitialAssessmentTime: "09-Mar-2031 10:16",
                AdmittedTime: "09-Mar-2031 15:27",
            },
        ],
        ADM: [
            {
                AdmitTime: "09-Mar-2031 15:27",
                AdmitUnit: "ED Unit #1",
                AdmitLocation: "ED Location #1",
                AdmitRoom: "ED Room #1",
                AdmitBed: "ED Bed #1",
                AdmittingPhysician: "Physician #1",
                AdmissionService: "Internal Medicine",
                DischargeTime: "14-Apr-2031 12:30",
                DischargeUnit: "Hospital Unit #2",
                DischargeLocation: "Hospital Location #2",
                DischargeRoom: "Hospital Room #2",
                DischargeBed: "Hospital BHospital #2",
                DischargePhysician: "Physician #2",
                DischargeService: "Orthopedic Surgery",

            },
        ],
        OrderEntry: [
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Cardiology",
                Procedure: "ECG-Adult(12Lead)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem7-GluR,Urea,Crea,Lytes",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "INR(PT)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "TroponinI",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "C-ReactiveProtein(CRP)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "D-Dimer",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "LiverFunctionTests(LFT)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "TroponinI",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Radiography",
                Procedure: "Chest(CXR)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Laboratory",
                Procedure: "BtypeNatriureticProtein",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "09-Mar-2031",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "11-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "11-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "12-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "12-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "09-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "ComputedTomography",
                Procedure: "AngioThoraxContrast(Pulm)",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "Albumin",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "Calcium",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "PeripheralBloodFilmSmear",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "Protein(Total)",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "ReticCount",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "NuclearMedicine",
                Procedure: "BONE",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "11-Mar-2031",
                Category: "Laboratory",
                Procedure: "ProteinElectrophoresis",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "UrineProteinElectrphRandom",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Laboratory",
                Procedure: "UrineRoutine(Urinalysis)",
            },
            {
                OrderDate: "10-Mar-2031",
                ServiceDate: "10-Mar-2031",
                Category: "Microbiology",
                Procedure: "MRSAScreen",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Radiography",
                Procedure: "SkeletalSurveyRoutine",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "BoneMarrowBooking",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "15-Mar-2031",
                Category: "Laboratory",
                Procedure: "Calcium",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "15-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "Beta2Microglobulin",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem4-Lytes(Na,K,Cl,Bicar)",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "Creatinine(EGFR)",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "Ferritin",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "FreelightChains,Serum",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "HepBSurfaceAntigen-Active",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "HepCAntibody",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "HIVSerology",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "IonizedCalciumProfile",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "LactateDehydrogenase(LDH)",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "ParathyroidHormone,Intact",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "ReticCount",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "14-Mar-2031",
                Category: "Laboratory",
                Procedure: "VitaminB12",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "15-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "14-Mar-2031",
                ServiceDate: "15-Mar-2031",
                Category: "Laboratory",
                Procedure: "ReticCount",
            },
            {
                OrderDate: "15-Mar-2031",
                ServiceDate: "15-Mar-2031",
                Category: "Physiotherapy",
                Procedure: "PhysiotherapyReferral",
            },
            {
                OrderDate: "16-Mar-2031",
                ServiceDate: "17-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem7-GluR,Urea,Crea,Lytes",
            },
            {
                OrderDate: "16-Mar-2031",
                ServiceDate: "17-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "16-Mar-2031",
                ServiceDate: "17-Mar-2031",
                Category: "Laboratory",
                Procedure: "IonizedCalciumProfile",
            },
            {
                OrderDate: "20-Mar-2031",
                ServiceDate: "21-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "20-Mar-2031",
                ServiceDate: "21-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "23-Mar-2031",
                ServiceDate: "23-Mar-2031",
                Category: "Physiotherapy",
                Procedure: "PhysiotherapyReferral",
            },
            {
                OrderDate: "24-Mar-2031",
                ServiceDate: "25-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "24-Mar-2031",
                ServiceDate: "25-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "24-Mar-2031",
                ServiceDate: "24-Mar-2031",
                Category: "Laboratory",
                Procedure: "BloodGas,Arterial(ABG)",
            },
            {
                OrderDate: "25-Mar-2031",
                ServiceDate: "25-Mar-2031",
                Category: "DietitianReferrals",
                Procedure: "NutritionAssessment",
            },
            {
                OrderDate: "27-Mar-2031",
                ServiceDate: "27-Mar-2031",
                Category: "OccupationalTherapy",
                Procedure: "OccupationalTherapyReferral",
            },
            {
                OrderDate: "27-Mar-2031",
                ServiceDate: "27-Mar-2031",
                Category: "Physiotherapy",
                Procedure: "PhysiotherapyReferral",
            },
            {
                OrderDate: "27-Mar-2031",
                ServiceDate: "27-Mar-2031",
                Category: "Radiography",
                Procedure: "ShoulderLt",
            },
            {
                OrderDate: "27-Mar-2031",
                ServiceDate: "27-Mar-2031",
                Category: "OccupationalTherapy",
                Procedure: "OccupationalTherapyReferral",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "ComputedTomography",
                Procedure: "ExtremityUpperLt",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "IonizedCalciumProfile",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Radiography",
                Procedure: "HumerusLt",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "TransfusionMedicalLaboratory",
                Procedure: "Group&Screen",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "TransfusionMedicalLaboratory",
                Procedure: "RedBloodCells(Crossmatch)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "BtypeNatriureticProtein",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "Ferritin",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "IronStudiesProfile",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "Magnesium",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "PeripheralBloodFilmSmear",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "Phosphorus(Phosphate)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Laboratory",
                Procedure: "ReticCount",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Radiography",
                Procedure: "Chest(CXR)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "28-Mar-2031",
                Category: "Cardiology",
                Procedure: "ECG-Adult(12Lead)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "30-Mar-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "30-Mar-2031",
                Category: "Laboratory",
                Procedure: "INR(PT)",
            },
            {
                OrderDate: "28-Mar-2031",
                ServiceDate: "30-Mar-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "30-Mar-2031",
                ServiceDate: "30-Mar-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "30-Mar-2031",
                ServiceDate: "30-Mar-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "30-Mar-2031",
                ServiceDate: "31-Mar-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "31-Mar-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Radiography",
                Procedure: "FluoroUpperExtLtSpecialist",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Radiography",
                Procedure: "HumerusLt",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Laboratory",
                Procedure: "INR(PT)",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "Laboratory",
                Procedure: "PartialThromboplastinTime",
            },
            {
                OrderDate: "01-Apr-2031",
                ServiceDate: "01-Apr-2031",
                Category: "ComputedTomography",
                Procedure: "ExtremityUpperLt",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Radiography",
                Procedure: "FluoroUpperExtLtSpecialist",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Radiography",
                Procedure: "HumerusLt",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Dietary",
                Procedure: "NothingByMouth",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "02-Apr-2031",
                ServiceDate: "02-Apr-2031",
                Category: "Radiography",
                Procedure: "ChestPortable",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "03-Apr-2031",
                Category: "Radiography",
                Procedure: "Chest(CXR)",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "03-Apr-2031",
                Category: "HomeHealth",
                Procedure: "HomeHealthLiasonReferral",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Dietary",
                Procedure: "General",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "05-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "05-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "06-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "06-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "05-Apr-2031",
                Category: "Radiography",
                Procedure: "Chest(CXR)",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "03-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "03-Apr-2031",
                ServiceDate: "03-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "04-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Laboratory",
                Procedure: "ImmunoglobulinA(IGA)",
            },
            {
                OrderDate: "04-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Laboratory",
                Procedure: "ImmunoglobulinG(IgG)",
            },
            {
                OrderDate: "04-Apr-2031",
                ServiceDate: "04-Apr-2031",
                Category: "Laboratory",
                Procedure: "ImmunoglobulinM(IGM)",
            },
            {
                OrderDate: "05-Apr-2031",
                ServiceDate: "06-Apr-2031",
                Category: "Laboratory",
                Procedure: "IonizedCalciumProfile",
            },
            {
                OrderDate: "06-Apr-2031",
                ServiceDate: "08-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "06-Apr-2031",
                ServiceDate: "08-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "09-Apr-2031",
                ServiceDate: "09-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "11-Apr-2031",
                ServiceDate: "12-Apr-2031",
                Category: "Laboratory",
                Procedure: "Chem6-Urea,Crea,Lytes",
            },
            {
                OrderDate: "11-Apr-2031",
                ServiceDate: "12-Apr-2031",
                Category: "Laboratory",
                Procedure: "CompleteBloodCount(CBC)",
            },
            {
                OrderDate: "12-Apr-2031",
                ServiceDate: "12-Apr-2031",
                Category: "Laboratory",
                Procedure: "LiverFunctionTests(LFT)",
            },
        ],
        Appointments: [
            {
                Date: "10-Mar-2031",
                Desctiption: "	CT ANGIO THORAX CONTRAST(PULM)",
                Dcotor: "Doctor #1",
                Location: "Location #1",
                Duration: "15 min",
            },
            {
                Date: "14-Mar-2031",
                Desctiption: "	NM BONE-WB INJ",
                Dcotor: "Doctor #1",
                Location: "Location #2",
                Duration: "10 min",
            },
            {
                Date: "14-Mar-2031",
                Desctiption: "	NM BONE-WB",
                Dcotor: "Doctor #1",
                Location: "Location #2",
                Duration: "45 min",
            },
            {
                Date: "14-Mar-2031",
                Desctiption: "	RA SKELETAL SURVEY ROUTINE",
                Dcotor: "Doctor #2",
                Location: "Location #3",
                Duration: "60 min",
            },
            {
                Date: "15-Mar-2031",
                Desctiption: "	LB BONE MARROW",
                Dcotor: "Doctor #3",
                Location: "Location #4",
                Duration: "60 min",
            },
        ],
        EDMLocationHistory: [{StartDate:"09-Mar-2031 10:01",
        EndDate:"10-Mar-2031 08:09",
        From:"Emergency Room #1",
        To:	"Emergency Room #2",
        Duration:"22.1 days",}],

    }];


    
    